# .circleci/config.yml
version: 2.1

# Circle CI arm64 builder

jobs:
  build-arm64:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    parameters:
      target-version-variant:
        type: string
    steps:
      - checkout
      - run: uname -a
      - run:
          name: Load Environment Variables from the .env file
          command: |
            set -a
            source .env
            set +a
            echo " "
            if [ -z "$REGISTRY" ] || [ -z "$REPO_NAME" ] || [ -z "$IMAGE_NAME" ]; then
              echo "Error: REGISTRY,REPO_NAME and IMAGE_NAME must be set" >&2
              exit 1
            else
              echo " ----  .env file loaded ----"
              echo " - REGISTRY: $REGISTRY"
              echo " - REPO_NAME: $REPO_NAME"
              echo " - IMAGE_NAME: $IMAGE_NAME"
            fi
      - run: docker --version
      - run: docker info
      - run: make test-<< parameters.target-version-variant >>
      - run: docker images

workflows:
  build-deploy:
    jobs:
      - build-arm64:
          matrix:
            parameters:
              target-version-variant: [
#
# They are created using the ./apply-ci.sh script based on the version.json file, 
#      where the architecture is defined as "arm64".
# These "--skip--" images serve as inputs for the "*-bundle" images,
#       hence they must be generated within the bundle JOB.
#
#circleci-targets-start
                "11-3.3-bookworm",
#   --skip--    "12-3.4-bookworm",  -->  generated with the related bundle job!
                "12-3.4-bundle-bookworm",
#   --skip--    "13-3.4-bookworm",  -->  generated with the related bundle job!
                "13-3.4-bundle-bookworm",
#   --skip--    "14-3.4-bookworm",  -->  generated with the related bundle job!
                "14-3.4-bundle-bookworm",
#   --skip--    "15-3.4-bookworm",  -->  generated with the related bundle job!
                "15-3.4-bundle-bookworm",
                "16-3.4-bookworm",
#circleci-targets-end
              ]
