# .circleci/config.yml
version: 2.1

# Circle CI arm64 builder
orbs:
  docker: circleci/docker@2.1.4

jobs:
  build-arm64:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    parameters:
      target-version-variant:
        type: string
    steps:
      - checkout
      - run: uname -a
      - run:
          name: Load Environment Variables from the .env file
          command: |
            set -a
            source .env
            set +a
            echo " "
            if [ -z "$REGISTRY" ] || [ -z "$REPO_NAME" ] || [ -z "$IMAGE_NAME" ]; then
              echo "Error: REGISTRY,REPO_NAME and IMAGE_NAME must be set" >&2
              exit 1
            else
              echo " ----  .env file loaded ----"
              echo " - REGISTRY: $REGISTRY"
              echo " - REPO_NAME: $REPO_NAME"
              echo " - IMAGE_NAME: $IMAGE_NAME"
            fi
      - run: docker --version
      - run: docker info
      - docker/check:
          registry: docker.io
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_ACCESS_TOKEN
      - run: make test-<< parameters.target-version-variant >>
      - run: docker images
      - run:
          name: Conditional Docker Check - Halt if not on master branch or if it's a PR
          command: |
            # Check if the current branch is NOT 'master' or if the build is triggered by a pull request.
            # If either of these conditions is met, halt the workflow.
            if [ "$CIRCLE_BRANCH" != "master" ] || [ -n "$CIRCLE_PULL_REQUEST" ]; then
              circleci-agent step halt
            fi



      - run:
          name: "Push docker image : make push-<< parameters.target-version-variant >>"
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ] && [ -z "$CIRCLE_PULL_REQUEST" ]; then
              make push-<< parameters.target-version-variant >>
            fi
#         environment:
#           DOCKERHUB_USERNAME: $DOCKERHUB_USERNAME
#           DOCKERHUB_ACCESS_TOKEN: $DOCKERHUB_ACCESS_TOKEN


workflows:
  build-deploy:
    triggers:
      - schedule:
          cron: "15 5 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-arm64:
          matrix:
            parameters:
              target-version-variant: [
#
# They are created using the ./apply-ci.sh script based on the version.json file,
#      where the architecture is defined as "arm64".
# These "--skip--" images serve as inputs for the "*-bundle" images,
#       hence they must be generated within the bundle JOB.
#
#circleci-targets-start
                "15-3.4-bookworm",
#circleci-targets-end
              ]
