name: "Localtest"
# testing the workflow
on:
  push:
  pull_request:
  schedule:
      - cron: '15 5 * * 1'

jobs:
  localtest:
    name: "testing ./localtest.sh ( update.sh and build test and push to local registry )"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: docker ps -a
      - run: pip3 install --upgrade pip
      - run: pip3 install --upgrade lastversion
      - run: tools/install_manifest-tool.sh
      - run: tools/environment_init.sh
      - run: ./localtest.sh
      - run: docker images
