# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Multi-Architecture Docker Manifest (Master)

on:
  workflow_dispatch:
  push:
    branches:
      - manifest  # Change to 'master' for production, 'manifest' for testing
    paths:
      - '.github/workflows/manifest-master.yml'
      - '.github/workflows/build-manifest-template.yml'
#multi-arch-paths-start
      - '16-master/bookworm/**'
      - '17-master/bookworm/**'
      - '18-master/bookworm/**'
#multi-arch-paths-end
  pull_request:
    paths:
      - '.github/workflows/manifest-master.yml'
      - '.github/workflows/build-manifest-template.yml'
#multi-arch-paths-start
      - '16-master/bookworm/**'
      - '17-master/bookworm/**'
      - '18-master/bookworm/**'
#multi-arch-paths-end

jobs:
  build-master:
    uses: ./.github/workflows/build-manifest-template.yml
    with:
      workflow_name: "Master"
      supported_architectures: '["amd64", "arm64"]'
      image_directories: '["16-master/bookworm", "17-master/bookworm", "18-master/bookworm"]'
      target_branch: "manifest"  # Change to 'master' for production, 'manifest' for testing
      registry: "docker.io"
      repo_name: "imresamu"
      image_name: "postgistest"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}