# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Other | Docker Multi-Arch Build Group

on:
  workflow_dispatch:
  push:
    branches:
      - manifest  # Change to 'master' for production, 'manifest' for testing
    paths:
      - '.github/workflows/manifest-other.yml'
      - '.github/workflows/build-manifest-template.yml'
#multi-arch-paths-start
      # Locked paths
      - '14-l3.1.9gcp/bookworm/**'
      # Master paths
      - '16-master/bookworm/**'
      - '17-master/bookworm/**'
      - '18-master/bookworm/**'
      # Recent paths
      - '16-recent/bookworm/**'
      - '17-recent/bookworm/**'
      - '18-recent/bookworm/**'
#multi-arch-paths-end
  pull_request:
    paths:
      - '.github/workflows/manifest-other.yml'
      - '.github/workflows/build-manifest-template.yml'
#multi-arch-paths-start
      # Locked paths
      - '14-l3.1.9gcp/bookworm/**'
      # Master paths
      - '16-master/bookworm/**'
      - '17-master/bookworm/**'
      - '18-master/bookworm/**'
      # Recent paths
      - '16-recent/bookworm/**'
      - '17-recent/bookworm/**'
      - '18-recent/bookworm/**'
#multi-arch-paths-end

jobs:
  # Step 1: Locked (1 directory, 1 architecture)
  locked:
    uses: ./.github/workflows/build-manifest-template.yml
    with:
      workflow_name: "Locked"
      supported_architectures: '["amd64"]'
      image_directories: '["14-l3.1.9gcp/bookworm"]'
      target_branch: "manifest"
      registry: "docker.io"
      repo_name: "imresamu"
      image_name: "postgistest"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

  # Step 2: Master (3 directories) - waits for Locked
  master:
    needs: locked
    uses: ./.github/workflows/build-manifest-template.yml
    with:
      workflow_name: "Master"
      supported_architectures: '["amd64", "arm64"]'
      image_directories: '["16-master/bookworm", "17-master/bookworm", "18-master/bookworm"]'
      target_branch: "manifest"
      registry: "docker.io"
      repo_name: "imresamu"
      image_name: "postgistest"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

  # Step 3: Recent (3 directories) - waits for Master
  recent:
    needs: master
    uses: ./.github/workflows/build-manifest-template.yml
    with:
      workflow_name: "Recent"
      supported_architectures: '["amd64", "arm64"]'
      image_directories: '["16-recent/bookworm", "17-recent/bookworm", "18-recent/bookworm"]'
      target_branch: "manifest"
      registry: "docker.io"
      repo_name: "imresamu"
      image_name: "postgistest"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}