# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Multi-Architecture Docker Manifest (Alpine 8-Arch)

on:
  workflow_dispatch:
  push:
    branches:
      - manifest  # Change to 'master' for production, 'manifest' for testing
    paths:
      - '.github/workflows/manifest-alpine-8arch.yml'
      - '.github/workflows/build-manifest-template.yml'
#multi-arch-paths-start
      - '13-3.5/alpine3.22/**'
      - '14-3.5/alpine3.22/**'
      - '15-3.5/alpine3.22/**'
      - '16-3.5/alpine3.22/**'
      - '17-3.5/alpine3.22/**'
      - '18-3.5/alpine3.22/**'
#multi-arch-paths-end
  pull_request:
    paths:
      - '.github/workflows/manifest-alpine-8arch.yml'
      - '.github/workflows/build-manifest-template.yml'
#multi-arch-paths-start
      - '13-3.5/alpine3.22/**'
      - '14-3.5/alpine3.22/**'
      - '15-3.5/alpine3.22/**'
      - '16-3.5/alpine3.22/**'
      - '17-3.5/alpine3.22/**'
      - '18-3.5/alpine3.22/**'
#multi-arch-paths-end

jobs:
  build-alpine-8arch:
    uses: ./.github/workflows/build-manifest-template.yml
    with:
      workflow_name: "Alpine-8Arch"
      supported_architectures: '["amd64", "arm64", "armv6", "armv7", "386", "ppc64le", "riscv64", "s390x"]'
      image_directories: '["13-3.5/alpine3.22", "14-3.5/alpine3.22", "15-3.5/alpine3.22", "16-3.5/alpine3.22", "17-3.5/alpine3.22", "18-3.5/alpine3.22"]'
      target_branch: "manifest"  # Change to 'master' for production, 'manifest' for testing
      registry: "docker.io"
      repo_name: "imresamu"
      image_name: "postgistest"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}