# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Multi-Architecture Docker Manifest (Bookworm)

on:
  workflow_dispatch:
  push:
    branches:
      - manifest  # Change to 'master' for production, 'manifest' for testing
    paths:
      - '.github/workflows/manifest-bookworm.yml'
      - '.github/workflows/build-manifest-template.yml'
#multi-arch-paths-start
      - '13-3.5/bookworm/**'
      - '14-3.5/bookworm/**'
      - '15-3.5/bookworm/**'
      - '18-3.5/bookworm/**'
#multi-arch-paths-end
  pull_request:
    paths:
      - '.github/workflows/manifest-bookworm.yml'
      - '.github/workflows/build-manifest-template.yml'
#multi-arch-paths-start
      - '13-3.5/bookworm/**'
      - '14-3.5/bookworm/**'
      - '15-3.5/bookworm/**'
      - '18-3.5/bookworm/**'
#multi-arch-paths-end

jobs:
  build-bookworm:
    uses: ./.github/workflows/build-manifest-template.yml
    with:
      workflow_name: "Bookworm"
      supported_architectures: '["amd64", "arm64"]'
      image_directories: '["13-3.5/bookworm", "14-3.5/bookworm", "15-3.5/bookworm", "18-3.5/bookworm"]'
      target_branch: "manifest"  # Change to 'master' for production, 'manifest' for testing
      registry: "docker.io"
      repo_name: "imresamu"
      image_name: "postgistest"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}