name: "update_dockerfiles"
# updating the image code and pushing to the local registry
on:
  schedule:
      - cron: '57 17 * * *'

jobs:
  update_dockerfiles:
    name: "update_dockerfiles"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: docker ps -a
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - run: pip3 install --upgrade pip
      - run: pip3 install --upgrade lastversion
      - run: tools/install_manifest-tool.sh
      - run: tools/environment_init.sh
      - run: ./update.sh
      - run: git status
      - run: git diff versions.json

      - name: Check if version.json changed
        id: version_check
        run: |
          if git diff --name-only | grep -q 'version.json'; then
            echo "version.json changed"
            # echo "versions_changed=true" >> $GITHUB_ENV
            # Generate changed versions list
            echo "versions_changed_list=$(./tools/get_versions_changes.sh)" >> $GITHUB_ENV
            echo "versions_changed_list=$(./tools/get_versions_changes.sh)"
            # Generate branch name with date and time
            echo "BRANCH_NAME=updates/$(date +'%Y%m%d_%H%M')" >> $GITHUB_ENV
          fi

      # https://github.com/peter-evans/create-pull-request
      - name: Create Pull Request
        if: env.version_changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.POSTGIS_PR_REPO_TOKEN }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit-message: Update version.json and related Dockerfiles
          title: '🤖 Bump the: ${{ env.versions_changed_list }}'
          body: |
            Update docker-postgis version.json and related Dockerfiles.
            Changes: ${{ env.versions_changed_list }}

            Auto-generated by .github/workflows/update.yml
            Please verify if the changes are correct!
          labels: automated_pr
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
