# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Debian | Docker Multi-Arch Build Workflow
# Updated test configuration for improved compatibility

permissions:
  actions: write
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Monday 02:00 UTC - Weekly Debian builds
  push:
    branches:
      - manifest  # Change to 'master' for production, 'manifest' for testing
    paths:
      - '.github/workflows/workflow-build-debian.yml'
      - '.github/workflows/template-workflow-multiarch.yml'
      - 'test/**'
#multi-arch-paths-start
      # Bookworm paths
      - '13-3.5/bookworm/**'
      - '14-3.5/bookworm/**'
      - '15-3.5/bookworm/**'
      - '18-3.5/bookworm/**'
      # Bundle0 paths
      - '16-3.5/bookworm/**'
      - '17-3.5/bookworm/**'
      - '16-3.5-bundle0/bookworm/**'
      - '17-3.5-bundle0/bookworm/**'
      # Bullseye paths
      - '13-3.5/bullseye/**'
      - '14-3.5/bullseye/**'
      - '15-3.5/bullseye/**'
      - '16-3.5/bullseye/**'
      - '17-3.5/bullseye/**'
#multi-arch-paths-end
  pull_request:
    paths:
      - '.github/workflows/workflow-build-debian.yml'
      - '.github/workflows/template-workflow-multiarch.yml'
      - 'test/**'
#multi-arch-paths-start
      # Bookworm paths
      - '13-3.5/bookworm/**'
      - '14-3.5/bookworm/**'
      - '15-3.5/bookworm/**'
      - '18-3.5/bookworm/**'
      # Bundle0 paths
      - '16-3.5/bookworm/**'
      - '17-3.5/bookworm/**'
      - '16-3.5-bundle0/bookworm/**'
      - '17-3.5-bundle0/bookworm/**'
      # Bullseye paths
      - '13-3.5/bullseye/**'
      - '14-3.5/bullseye/**'
      - '15-3.5/bullseye/**'
      - '16-3.5/bullseye/**'
      - '17-3.5/bullseye/**'
#multi-arch-paths-end

env:
  WORKFLOW_CACHE_ID: "deb"  # Debian workflow cache identifier

jobs:
  # =============================================================================
  # DEBIAN MULTI-ARCHITECTURE BUILD PIPELINE (3 STEPS)
  # =============================================================================
  # 
  # This workflow builds Docker images for 2 architectures (amd64, arm64) across
  # 3 priority-based steps with descending PostgreSQL version order (18→13).
  #
  # STEP 1: "Bookworm [1/3]" (6 directories) - Base images (highest priority)
  #   build(-amd64): 18-3.5/bookworm → 17-3.5/bookworm → 16-3.5/bookworm → 15-3.5/bookworm → 14-3.5/bookworm → 13-3.5/bookworm
  #   build(-arm64): 18-3.5/bookworm → 17-3.5/bookworm → 16-3.5/bookworm → 15-3.5/bookworm → 14-3.5/bookworm → 13-3.5/bookworm
  #   manifest(amd64+arm64): 18-3.5/bookworm → 17-3.5/bookworm → 16-3.5/bookworm → 15-3.5/bookworm → 14-3.5/bookworm → 13-3.5/bookworm
  #
  # STEP 2: "Bullseye [2/3]" (5 directories) - Alternative base (depends on Step 1)
  #   build(-amd64): 17-3.5/bullseye → 16-3.5/bullseye → 15-3.5/bullseye → 14-3.5/bullseye → 13-3.5/bullseye
  #   build(-arm64): 17-3.5/bullseye → 16-3.5/bullseye → 15-3.5/bullseye → 14-3.5/bullseye → 13-3.5/bullseye
  #   manifest(amd64+arm64): 17-3.5/bullseye → 16-3.5/bullseye → 15-3.5/bullseye → 14-3.5/bullseye → 13-3.5/bullseye
  #
  # STEP 3: "Bundle0 [3/3]" (2 directories) - Extended bundles (depends on Step 2)
  #   build(-amd64): 17-3.5-bundle0/bookworm → 16-3.5-bundle0/bookworm
  #   build(-arm64): 17-3.5-bundle0/bookworm → 16-3.5-bundle0/bookworm
  #   manifest(amd64+arm64): 17-3.5-bundle0/bookworm → 16-3.5-bundle0/bookworm
  # =============================================================================

  # Step 1: Bookworm base images (priority: highest - base images needed for everything)
  bookworm:
    name: "Bookworm [1/3]"
    uses: ./.github/workflows/template-workflow-multiarch.yml
    with:
      workflow_name: "Bookworm [1/3]"
      supported_architectures: '["amd64", "arm64"]'
      image_directories: '["18-3.5/bookworm", "17-3.5/bookworm", "16-3.5/bookworm", "15-3.5/bookworm", "14-3.5/bookworm", "13-3.5/bookworm"]'
      target_branch: "manifest"
      registry: "docker.io"
      repo_name: "imresamu"
      image_name: "postgistest"
      workflow_cache_id: "deb"
      schedule_parallel: 6
      manual_parallel: 4
      push_pr_parallel: 2
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

  # Step 2: Bullseye (priority: medium - depends on Bookworm base images)
  bullseye:
    name: "Bullseye [2/3]"
    needs: bookworm
    uses: ./.github/workflows/template-workflow-multiarch.yml
    with:
      workflow_name: "Bullseye [2/3]"
      supported_architectures: '["amd64", "arm64"]'
      image_directories: '["17-3.5/bullseye", "16-3.5/bullseye", "15-3.5/bullseye", "14-3.5/bullseye", "13-3.5/bullseye"]'
      target_branch: "manifest"
      registry: "docker.io"
      repo_name: "imresamu"
      image_name: "postgistest"
      workflow_cache_id: "deb"
      schedule_parallel: 6
      manual_parallel: 4
      push_pr_parallel: 2
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

  # Step 3: Bundle0 (priority: lowest - depends on Bookworm base images being available)
  bundle0:
    name: "Bundle0 [3/3]"
    needs: [bookworm, bullseye]
    uses: ./.github/workflows/template-workflow-multiarch.yml
    with:
      workflow_name: "Bundle0 [3/3]"
      supported_architectures: '["amd64", "arm64"]'
      image_directories: '["17-3.5-bundle0/bookworm", "16-3.5-bundle0/bookworm"]'
      target_branch: "manifest"
      registry: "docker.io"
      repo_name: "imresamu"
      image_name: "postgistest"
      workflow_cache_id: "deb"
      schedule_parallel: 4
      manual_parallel: 3
      push_pr_parallel: 2
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

  # =============================================================================
  # AUTO-RETRY FAILED JOBS
  # =============================================================================

  auto-retry-failed:
    name: "🔄 Auto-retry failed Debian builds"
    needs:
      - bookworm
      - bullseye
      - bundle0
    if: always()
    uses: ./.github/workflows/template-workflow-auto-retry.yml
    with:
      workflow_name: "Debian"
      workflow_emoji: "📦"
      job_names: '["bookworm", "bullseye", "bundle0"]'
      workflow_cache_id: "deb"
      max_attempts: 3
      enable_detailed_logging: true